name: 'Setup Environment and Cache Dependencies'
description: 'Setup Python and Cache dependencies'

inputs:
  python-version:
    description: 'Version of Python to set up'
    required: false
    default: '3.8.17'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      id: python
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache@v3
      id: dependency-cache
      with:
        path: .venv
        key: python-venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('**/setup.py') }}
    - if: steps.dependency-cache.outputs.cache-hit != 'true'
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -e '.[testing,linting,llvm,cuda]' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: bash