name: 'Setup Environment and Restore Cache'
description: 'Setup Python and Restore Cache dependencies'

inputs:
  python-version:
    description: 'Version of Python to set up'
    required: false
    default: '3.8.17'
  install-llvm:
    description: 'Re-install LLVM'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      id: python
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache/restore@v3
      id: dependency-cache
      with:
        path: .venv
        key: python-venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('**/setup.py') }}
    - if: steps.dependency-cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[testing,linting,llvm]' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: bash
    - if: steps.dependency-cache.outputs.cache-hit == 'true' && ${{ inputs.re-install-llvm }} == 'true'
      run: source .venv/bin/activate && pip install -e '.[llvm]'
      shell: bash
