name: 'Setup Python and Restore Cache Dependencies'
description: 'Wrapper around actions/setup-python with pip caching that actually works'
inputs:
  python-version:
    description: 'Version of Python to set up.'
    required: true
  pip-install:
    description: 'Use to change what pip installs. Example: ''.[testing]'' Default: . (required dependencies)'
    required: false
    default: '.'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache/restore@v3
      id: dependency-cache
      with:
        path: ${{ steps.setup-python.outputs.python-path }}
        key: ${{ runner.os }}-python${{ inputs.python-version }}-${{ hashFiles(format('{0}',inputs.pip-install)) }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-python${{ inputs.python-version }}-${{ hashFiles('.') }}-
    - if: |
        steps.dependency-cache.outputs.cache-hit != 'true' && 
        (runner.os == 'Linux' || runner.os == 'macOS')
      run: |
        python -m pip install --upgrade pip
        pip install -e '${{ inputs.pip-install }}' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: bash
    - if: |
        steps.dependency-cache.outputs.cache-hit != 'true' &&
        runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -e '${{ inputs.pip-install }}' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: pwsh
