name: 'Setup Environment and Restore Cache'
description: 'Setup Python and Restore Cache dependencies'

inputs:
  python-version:
    description: 'Version of Python to set up. Make sure to use the major.minor version, e.g. 3.8 not 3.8.17'
    required: true
  depends:
    # TODO: Has to be a better way to do this, check python-cache.yml for more info
    description: 'Dependency to restore from cache. e.g. "testing", "testing,linting".'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      id: python
      with:
        python-version: ${{ inputs.python-version }}
    - uses: actions/cache/restore@v3
      id: dependency-cache
      with:
        path: .venv
        key: ${{ runner.os }}.python-${{ inputs.python-version }}.dependencies[${{ inputs.depends }}]-${{ hashFiles('**/setup.py') }}
    - if: steps.dependency-cache.outputs.cache-hit != 'true' && (runner.os == 'Linux' || runner.os == 'macOS')
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[${{ inputs.depends }}]' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: bash
    - if: steps.dependency-cache.outputs.cache-hit != 'true' && runner.os == 'Windows'
      run: |
        python -m pip install --upgrade pip
        pip install -e '.[${{ inputs.depends }}]' --extra-index-url https://download.pytorch.org/whl/cpu
      shell: powershell